// Generated by CoffeeScript 1.4.0
(function() {
  var LANGS, TTS, app, getRandomInt;

  getRandomInt = function(min, max) {
    return Math.floor(Math.random() * (max - min)) + min;
  };

  TTS = (function() {

    function TTS() {
      this.audio = new Audio();
    }

    TTS.prototype.play = function(lang, text) {
      this.audio.pause();
      this.audio.src = "http://translate.google.com/translate_tts?tl=" + lang + "&q=" + text + "&total=1&idx=0";
      return this.audio.play();
    };

    return TTS;

  })();

  app = angular.module('numbersApp', []);

  app.controller('gameCtrl', function($scope) {
    var tts;
    tts = new TTS();
    $scope.correct = 0;
    $scope.total = 0;
    $scope.value = null;
    $scope.correct_answer = null;
    $scope.next = function() {
      if ($scope.value != null) {
        if (parseInt($scope.answer) === $scope.value) {
          $scope.correct_answer = null;
          $scope.correct++;
        } else {
          $scope.correct_answer = $scope.value;
        }
        $scope.total++;
        $scope.answer = '';
      }
      $scope.value = getRandomInt($scope.min, $scope.max);
      return tts.play($scope.language, $scope.value);
    };
    return $scope.started = function() {
      return $scope.value != null;
    };
  });

  app.controller('ctrl', function($scope) {
    $scope.LANGS = LANGS;
    $scope.language = localStorage.getItem('lang') || 'en';
    $scope.min = parseInt(localStorage.getItem('min')) || 0;
    $scope.max = parseInt(localStorage.getItem('max')) || 99999;
    $scope.$watch('language', function() {
      return localStorage.setItem('lang', $scope.language);
    });
    $scope.$watch('min', function() {
      return localStorage.setItem('min', $scope.min);
    });
    return $scope.$watch('max', function() {
      return localStorage.setItem('max', $scope.max);
    });
  });

  LANGS = {
    'af': 'Afrikaans',
    'sq': 'Albanian',
    'ar': 'Arabic',
    'hy': 'Armenian',
    'ca': 'Catalan',
    'zh-CN': 'Mandarin (simplified)',
    'zh-TW': 'Mandarin (traditional)',
    'hr': 'Croatian',
    'cs': 'Czech',
    'da': 'Danish',
    'nl': 'Dutch',
    'en': 'English',
    'eo': 'Esperanto',
    'fi': 'Finnish',
    'fr': 'French',
    'de': 'German',
    'el': 'Greek',
    'ht': 'Haitian Creole',
    'hi': 'Hindi',
    'hu': 'Hungarian',
    'is': 'Icelandic',
    'id': 'Indonesian',
    'it': 'Italian',
    'ja': 'Japanese',
    'ko': 'Korean',
    'la': 'Latin',
    'lv': 'Latvian',
    'mk': 'Macedonian',
    'no': 'Norwegian',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ro': 'Romanian',
    'ru': 'Russian',
    'sr': 'Serbian',
    'sk': 'Slovak',
    'es': 'Spanish',
    'sw': 'Swahili',
    'sv': 'Swedish',
    'ta': 'Tamil',
    'th': 'Thai',
    'tr': 'Turkish',
    'vi': 'Vietnamese',
    'cy': 'Welsh'
  };

}).call(this);
